import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotoFont = Roboto({
    subsets: ["latin"],
    variable: "--font-roboto",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${robotoFont.className} bg-color-background`}>
                <div className="min-w-auto mx-52 ">{children}</div>
            </body>
        </html>
    );
}
